modulesync 2021-07-13
voxpupuli/puppet-lint-optional_default-check pull request #3
Opened 2021-07-13 18:29 UTC by bastelfreak

2021-07-13 19:10 UTC, bastelfreak commented
well that took some time... @alexjfisher I tried to implement the suggestions from https://github.com/voxpupuli/voxpupuli-test/pull/43 for codecov reporting but it doesn't respond in this PR. Any ideas?

2021-07-13 21:09 UTC, alexjfisher requested changes

2021-07-13 21:09 UTC, alexjfisher commented on README.md
> +[![Donated by Camptocamp](https://img.shields.io/badge/donated%20by-camptocamp-fb7047.svg)](#transfer-notice)
Oi!

2021-07-13 21:12 UTC, bastelfreak commented on README.md
> +[![Donated by Camptocamp](https://img.shields.io/badge/donated%20by-camptocamp-fb7047.svg)](#transfer-notice)
fixed it

2021-07-20 09:38 UTC, alexjfisher approved these changes

2021-07-20 09:51 UTC, merged